spring:
#  data:
#    elasticsearch:
#      cluster-name: esDemo
#      cluster-nodes: 192.168.25.131:9300
#      repositories:
#        enabled: true
  #此操作会覆盖bean 不要使用
  #main:
    #allow-bean-definition-overriding: true
  rabbitmq:
    #host: 192.168.25.130
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.27.128:3307/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
  redis:
    host: 192.168.27.128
    port: 6379
  mvc:
    static-path-pattern: /static/**
#  batch:
#    schema:
#      - classpath:sql/

mybatis:
  config-location: classpath:mybatis/config-mybais.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.wjl.blog.mapper : debug
#启动端口
server:
  port: 1314
#es配置类
elasticSearch:
  hostlist: 192.168.27.128:9200
  client:
    connectNum: 10
    connectPerRoute: 50
